# Generated by Django 6.0.2 on 2026-02-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('format', models.CharField(choices=[('MTT', 'MTT'), ('SNG', 'SNG'), ('CASH', 'Cash')], default='MTT', max_length=10)),
                ('buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rake', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('table_count', models.PositiveIntegerField(blank=True, null=True)),
                ('mood', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
