# Generated by Django 6.0.2 on 2026-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ev_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit for this session', max_digits=10, null=True),
        ),
    ]
