# Generated by Django 6.0.2 on 2026-02-22 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerlog', '0002_entry_ev_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bankroll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_buyin_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Max buy-in as % of bankroll (e.g. 2.00 = 2%)', max_digits=5)),
                ('stop_loss_buyins', models.DecimalField(decimal_places=2, default=5.0, help_text='Stop-loss in buy-ins per day/session block', max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
