# Generated by Django 6.0.2 on 2026-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerlog', '0006_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
